### ISSUE TITLE
Upgrade issue

### ISSUE THREAD

**Issue by yueyingsk** [Tapadoo/Alerter#100]
I found that the default bell turned black when I upgraded from 2.0.0 to 2.0.2，But there is no method "setProgressColorRes" in version 2.0.0，So what's the problem with the new version?Oh, by the way, I went back to version 2. 0. 0 and the default bell changed back to white.

**Comment by kpmmmurphy** [comment]
Thanks for your feedback @yueyingsk. This has been fixed in version 2.0.3.
