### ISSUE TITLE
The progress bar is not shown and the icon is black

### ISSUE THREAD

**Issue by jonathansilva** [Tapadoo/Alerter#109]
the version is 2.0.2

`public static void alerter(Integer title, Activity activity) {`
`Alerter.create(activity)`
`.setTitle(title)`
`.setBackgroundColorRes(R.color.colorPrimary)`
`.setDuration(2000)`
`.enableProgress(true)`
`.setProgressColorRes(R.color.colorGreenDark)`
`.show();`
`}`

`Helper.alerter(R.string.response_error, getActivity());`

![sem titulo2](https://user-images.githubusercontent.com/33843748/35251615-19e33eea-ffc3-11e7-8d2a-79353b29b16d.png)

**Comment by kpmmmurphy** [comment]
Hi @jonathansilva,

Icon tint has been fixed in version 2.0.3. Now the icon is tinted white by default, and this can be turned off by - 

```java
Alerter.create(this)
       .setText("Alert text...")
       .setIcon(R.drawable.alerter_ic_mail_outline)
       .setIconColorFilter(0) // Removes white tint
       .show();
```

I cannot replicate the issue you're having with the progress bar - Ensure your colours are correct.
