### ISSUE TITLE
Icons ignoring color in release 2.0.3

### ISSUE THREAD

**Issue by TeTRA99** [Tapadoo/Alerter#110]
It seems that all icons I was using in the alerter turned white with the latest 2.0.3 release. Did any method/property change? Going back to 2.0.2 put them back in color.

**Comment by kpmmmurphy** [comment]
Hi @TeTRA99, yes the library tints the icon white by default. To disable it, you can do - 

```java
Alerter.create(this)
       .setText("Alert text...")
       .setIcon(R.drawable.alerter_ic_mail_outline)
       .setIconColorFilter(0) // Removes white tint
       .show();
```
