### ISSUE TITLE
How do I set text color of the alert?

### ISSUE THREAD

**Issue by mayuroks** [Tapadoo/Alerter#114]
I am getting black as default font color. I want to set it to white. How can I do it?

**Comment by jkeyes** [comment]
@mayuroks See https://github.com/Tapadoo/Alerter/issues/110#issuecomment-360525750

**Comment by kpmmmurphy** [comment]
This can be done by creating a new style in your styles.xml, like - 

```xml 

<style name="AlertTextAppearance">
        <item name="android:textColor">#fff</item>
</style>
```

And then applying it to the Alerter builder - 

```java
Alerter.create(DemoActivity.this)
                .setTitle("Alert Title")
                .setTitleAppearance(R.style.AlertTextAppearance)
                .setText("Alert text...")
                .show();

```
