### ISSUE TITLE
Proposal of logo and icon for the application

### ISSUE THREAD

**Issue by richardbmx** [Tapadoo/Alerter#122]
Hello I would like to contribute with a new icon and logo for your application I leave you the proposal if you want to use it I can send you all the files.

![presentacion para github.png](https://steemitimages.com/DQmckxkk7yiq23YFouykBtw2h7yzaWgyFtqkAY4LJdAtJZv/presentacion%20para%20github.png)

**Comment by kpmmmurphy** [comment]
Hi @richardbmx, many thanks for your contribution. I think we'll continue with the original icon for now, but nice work!
