### ISSUE TITLE
Show over all activities.

### ISSUE THREAD

**Issue by pingothedoer** [Tapadoo/Alerter#123]
Is there any way that i could show over everything else going below this alert just like Toast. I know Alerter requires Activity context to show, But if i create an alerter from one activity and switch to next activity, i want the alerter to be shown there as well. 

I have tried using some BaseActivity as well. But same result.

**Comment by kpmmmurphy** [comment]
The way the Alerter works is by attaching a view to the current Activity's DecorView, or Window - each Activity maintains its own DecorView/Window - so the functionality you're looking for isn't supported, and I'm not sure how exactly it would be implemented. I'd love to review a pull request, if you're experimenting with this.
