### ISSUE TITLE
new logo/icon

### ISSUE THREAD

**Issue by mansya** [Tapadoo/Alerter#133]
Hi, I am a graphic designer, I want to help others in graphic design.

After I reviewed your project, your logo on this project is generic and unatractive. Therefore I want to contribute to this project by creating a new logo / icon. what do you think?

**Comment by kpmmmurphy** [comment]
Hi @mansya, absolutely, post a draft here, and we can can review. Many thanks.

**Comment by mansya** [comment]
I have design a logo for this project. what do you think ? which one do you like it ?
![alerter](https://user-images.githubusercontent.com/33461607/42133125-8f91854e-7d4e-11e8-8cf6-012d535c2fa2.png)

**Comment by kpmmmurphy** [comment]
Hey @mansya, thanks very much for submitting the logo! While I think what you've created here is good, I don't think it fits the feel of the library.

**Comment by mansya** [comment]
I have redesigned. What do you think ? do you like it ?
![alerter](https://user-images.githubusercontent.com/33461607/42413491-a0848156-824b-11e8-936a-fe0512452f84.png)

**Comment by kpmmmurphy** [comment]
Hi @mansya, thanks for the updated logo. This one is a big improvement on the first. Feel free to create a pull request with the logo included, and add me as a reviewer. Many thanks.

**Comment by mansya** [comment]
I have replace the old icon with new icon. but for the banner on the display page I have not changed it. and I've designed it. you can change it yourself

for all files I have uploaded into this link.
https://drive.google.com/open?id=1BmNGA61vAKHYOCGYFW1LJPd8Jd0fqEy-

And I have sent you pull requests. please check it.
