### ISSUE TITLE
App crashed when using the alerter library

### ISSUE THREAD

**Issue by ArigarasuthanRepo** [Tapadoo/Alerter#138]
Iam using alerter library for my android app.When i set the alerter in my activity iam getting this error

java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics

**Comment by longer96** [comment]
+1

**Comment by kpmmmurphy** [comment]
Hi @ArigarasuthanRepo, 

Thanks for flagging this issue. Please revert to version 2.0.6 of the library for now, there seems to be an issue with Jetpack & AndroidX dependencies. Investigating now.

**Comment by ArigarasuthanRepo** [comment]
Ok thank you.

**Comment by leobrujah** [comment]
@kpmmmurphy I'd say because the project is now on Kotlin, you have to add kotlin dependency in your project in order to work, the same with `constraintlayout` seems like it doesn't solve the dependency from the library and you have to add it in your project as well. You can reproduce the error by creating an empty java project and add Alerter as the only dependency, it won't work unless you add kotlin + constraintlayout

**Comment by kpmmmurphy** [comment]
You're right, good catch @leobrujah, compatibility with Jetpack & AndroidX appears to be a separate issue. I will add some documentation with the requirements for integrating version 3.0.0 of the library.

**Comment by moda20** [comment]
This is still not resolved I guess, I am having problems with the `contraintlayout`being not found.
`layout_constraintBottom_toBottomOf) not found.`

**Comment by playscforever** [comment]
+10000

**Comment by kpmmmurphy** [comment]
As a temporary workaround, add this to your dependencies in your build.gradle:

`implementation 'com.android.support.constraint:constraint-layout:1.1.2'`

**Comment by waseefakhtar** [comment]
Is the documentation for integrating version 3.0.0 available yet? I've updated my library from 2.0.5 and receiving this error while adding it into a Java project. How do we make sure it runs with Java?

**Comment by waseefakhtar** [comment]
For those who're struggling, I got this working by using Tools > Kotlin > Configure Kotlin in Project. If you don't have the option, you can manually configure it by:

1. Adding the following to the project build.gradle:

```
buildscript {
    ext.kotlin_version = '1.2.70'

    repositories {
      mavenCentral()
    }

    dependencies {
      classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
```

2. Adding the following to the module build.gradle:

```
apply plugin: 'kotlin-android'

buildscript {
    repositories {
        mavenCentral()
    }
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}
```

**Comment by kpmmmurphy** [comment]
Sorry for the delay on this! I've updated the README to notify devs that Kotlin is required, and I've removed the ConstraintLayout dependency.

**Comment by cr05s19xx** [comment]
Can you please make it clearer? It is very easy to skip over in the README

**Comment by prathamesh22davande** [comment]
thanks for solution Waseefakhtar
