### ISSUE TITLE
Setting hideIcon() or showIcon(false) has no effect

### ISSUE THREAD

**Issue by mecoFarid** [Tapadoo/Alerter#140]
I have tried to hide icon by using two methods `hideIcon()` or `showIcon(false)`, but none took effect. Icon is still visible.

**Comment by oHoangVanTuan** [comment]
You can try using method `.enableIconPulse(false)`

**Comment by mecoFarid** [comment]
That removes the icon totally

**Comment by mecoFarid** [comment]
It is not intended use, I believe. Also, setting it to `false` leaves the icon `INVISIBLE` not `GONE`, I mean there is still space before the title and body of `Alerter`.
