### ISSUE TITLE
Strange behaviour using click TextView as the event to trigger alerter

### ISSUE THREAD

**Issue by diogobernardino** [Tapadoo/Alerter#15]
I've run into a strange behaviour while defining an `OnClickListener` in a `TextView` in order to show an alerter. It doesn't show at the first click, while the second triggers it twice. You can observe the same behaviour every second click. I just reproduced it in the example application by adding a `TextView` to the layout and:

```
@Override
protected void onCreate(Bundle savedInstanceState) {
         
    ...
        
    findViewById(R.id.textttt).setOnClickListener(new View.OnClickListener() {
        @Override
        public void onClick(View v) {
            showAlertDefault();
        }
    });
}
```

**Comment by kpmmmurphy** [comment]
Thanks for flagging - I'll look into it.

**Comment by diogobernardino** [comment]
And the same happens with `ImageButton`.

**Comment by kpmmmurphy** [comment]
Hi @diogobernardino - I can't reproduce this. I've tried both the `TextView` & `ImageButton`.

**Comment by diogobernardino** [comment]
Really? Ok, then I need to give it a try in a real device, maybe the problem was the emulator.

**Comment by kpmmmurphy** [comment]
Please do. I was using a OnePlus 2 to test, and both perform correctly - Using library version 1.0.3.

**Comment by diogobernardino** [comment]
Unfortunately I do see the problem even in a real device (Nexus 5X). And again, in order to discard a problem in my layout, I used the example app and even there I see these hiccups. Though everything works fine if instead of an Alerter I use a normal android Toast. I'm confused...

Thinking out loud... the first notification shows fine, but after that one it feels like the app loses the focus and clicking again nothing happens. Unless you click again or, you click in something else in the app which forces a display re draw.

Maybe we will need to wait until someone else gets the same.
