### ISSUE TITLE
Didn't find class "kotlin.jvm.internal.Intrinsics" on path: DexPathList[[zip file 

### ISSUE THREAD

**Issue by Nancyls** [Tapadoo/Alerter#152]
Didn't find class "kotlin.jvm.internal.Intrinsics" on path: DexPathList[[zip file ....

java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;...

AS3.1,tool3.1.4

solvetion:
implementation 'com.tapadoo.android:alerter:3.0.1'
implementation 'com.mapzen:on-the-road:1.3.1'

**Comment by p4r460n** [comment]
Same issue with me.

**Comment by p4r460n** [comment]
Maybe it needs Kotlin configured in project.

**Comment by Nancyls** [comment]
> Maybe it needs Kotlin configured in project.

sorry ,i do not konw ,but my app is running now
