### ISSUE TITLE
View shows behind DialogFragment

### ISSUE THREAD

**Issue by webnizam** [Tapadoo/Alerter#159]
I was trying to implement this in my app from a DialogFragment.

The view is showing, but the problem is it's behind the DialogFragment, hence it's not visible to see from dialog screen.

Any Solution ?

**Comment by kpmmmurphy** [comment]
Hey @webnizam, 

There's no supported solution to this right now unfortunately. I believe DialogFragments share the same window as the enclosing Activity, which the Alerter is added to. One possibility is changing the translationZ of the Alert view to force it above everything else, but I'm not certain if that would solve your issue!
