### ISSUE TITLE
Support Alerter to show in the middle or from bottom

### ISSUE THREAD

**Issue by nabil6391** [Tapadoo/Alerter#163]
Hi, I love your library... it has the potential to replace traditional popups and dialogs. I would like to use Alerter in all places ... its so easy to use and has all necessary functions.

Can you please see if you can support alerter to be viewable in the center like a popup or from the bottom like a snackbar

**Comment by kldMohammed** [comment]
i also need this feature to be added

**Comment by rezaiyan** [comment]
I'll do this

**Comment by kldMohammed** [comment]
> ERROR: Failed to resolve: com.tapadoo.android:alerter:5.1.0 


do you update version ? cause i can not found it 

i took version number 5.1.0 from your commit

**Comment by kpmmmurphy** [comment]
Apologies, just merged into Master. A new build should be ready in the next 30 minutes.
