### ISSUE TITLE
Alerter text cutting off in new android 9.0 notch

### ISSUE THREAD

**Issue by hamrashees** [Tapadoo/Alerter#164]
#<img width="275" alt="screen shot 2018-11-21 at 3 52 15 pm" src="https://user-images.githubusercontent.com/31973995/48867903-c24ccd00-eda5-11e8-96d0-08f367461e58.png">

After updating my android to Android 9 and having a notch enabled, I encountered this issue in alerter. The text cuts off because of the notch. Is there any fix we can have to support this?

**Comment by kpmmmurphy** [comment]
I've added a fix for this in version 4.0.0
