### ISSUE TITLE
hide method is private

### ISSUE THREAD

**Issue by bernaferrari** [Tapadoo/Alerter#167]
I just updated to v4 and hide method is now private, how am I supposed to use it?
(kind of similar: https://github.com/Tapadoo/Alerter/issues/34)

**Comment by kpmmmurphy** [comment]
Hi @bernaferrari, apologies for the delay in response. Are you using Kotlin, or Java? The Alerter can be dismissed by calling the static `hide()` method like this: 

```kotlin
 Alerter.hide()
```

Does this solve your issue?

**Comment by bernaferrari** [comment]
Thanks!! Yes, I didn't see it.

**Comment by AvatarQing** [comment]
` Alerter.hide()` will remove all alert views in current acitivty, but I want to remove current alert view only, it seems not supported yet
