### ISSUE TITLE
new version app crashing.

### ISSUE THREAD

**Issue by TowardInfinity** [Tapadoo/Alerter#169]
I am building an **Android** project, was implementing Alerter 4.0.0 as it supports **Notch** as well.
`    implementation 'com.tapadoo.android:alerter:4.0.0'
`
and wrote very basic Alert and my app started crashing.

`
![image](https://user-images.githubusercontent.com/34218629/51358146-0f1ffc00-1ae8-11e9-8909-7c777aff1c68.png)

`
i think there is a bug in the latest version.

**Comment by kpmmmurphy** [comment]
Hey @TowardInfinity, thanks for flagging this. I'll investigate. What device, and version of Android are you using?

**Comment by TowardInfinity** [comment]
No, i am not using AndroidX.

**Comment by kpmmmurphy** [comment]
Version 4.0.0 uses AndroidX, so this is a requirement.

**Comment by TowardInfinity** [comment]
I added, 
```
android.useAndroidX=true
android.enableJetifier=true
```
these to my gradle.properties.
Build finished but when i try to run on my device, compilation failed.

**Comment by TowardInfinity** [comment]
It is working as i migrated my app to AndroidX. Hope to see the update soon for Android.
