### ISSUE TITLE
Multiple clicks  opens multiple alerts

### ISSUE THREAD

**Issue by ArisChoice** [Tapadoo/Alerter#17]
How to handle  this scenario?

**Comment by kpmmmurphy** [comment]
Can you give me a little more detail please?

**Comment by RamolaWeb** [comment]
@kpmmmurphy we must use the same alerter for displaying the alert instead of hiding the alerter and showing the new one.

**Comment by KingJA** [comment]
Maybe singleton can solve this "bug",but in most cases,you won't create and show the Alert many times in a short time.

**Comment by ArisChoice** [comment]
Please Check this,
This is what actually happening on multiple click.[https://www.dropbox.com/s/qom38n9dn8swme8/device-2017-02-22-150516.mp4?dl=0](url)

**Comment by kpmmmurphy** [comment]
@RamolaWeb Can you put in a pull request with the functionality you desire, and I can review?

@KingJA It was deliberately designed that way, so it's not a bug. 

@ArisChoice I'm getting a 404 with that link.

**Comment by ArisChoice** [comment]
@kpmmmurphy  Can we handle  this flickering. That is the  point ,BTW  this is awesome library.

**Comment by kpmmmurphy** [comment]
@ArisChoice Thanks for the video! I'll see if I can improve on this. Just a suggestion but - It could be solved in your app, by disabling the submit button when the network is unavailable?

**Comment by ArisChoice** [comment]
Thanks , :+1:   But this is a sample,What i wants to show u.@kpmmmurphy
