### ISSUE TITLE
 The function works normally, but an error message is output.

### ISSUE THREAD

**Issue by traeumen927** [Tapadoo/Alerter#174]
Hello

I use Alerter well.

However, after the Alerter is shown, the following error message is printed on the console.

```
 Alerter.create(activity)
    .setTitle("Login fail")
    .setText("Check your password")
    .setBackgroundColorInt(Color.parseColor("#e74c3c"))
    .show()
```

> E/: getParent() returning Null

Fortunately, the program does not stop or terminate, but I'm afraid it's a problem.

> Development environment
> alerter:3.0.1
> kotlin 1.3.10
> android.tools.build:gradle:3.3.1'

When using alerter version 4.0.0, I am using 3.0.1 because of an error.

Thank you.

**Comment by kpmmmurphy** [comment]
Thanks for logging this, I've removed this print log in version 4.0.1.
