### ISSUE TITLE
setDismissable in not working

### ISSUE THREAD

**Issue by taimur44** [Tapadoo/Alerter#179]
Hi, 

The Alerter is so good. Love this library. 
Thank you for providing this library 

I do not want to dismiss the alert until the user will not cancel it. So i used **setDismissable** function. But it's not working. Please check the below code 

`      Alerter.create(this)
                .setTitle("Delete")
                .setText("Are you sure you want to delete?")
                .setTitleAppearance(R.style.AlertTextAppearance_Title)
                .setTitleTypeface(Typeface.createFromAsset(context.getAssets(), "roboto_medium.ttf"))
                .setTextTypeface(Typeface.createFromAsset(context.getAssets(), "roboto_regular.ttf"))
                .setTextAppearance(R.style.AlertTextAppearance_Text)
                .enableVibration(true)
                .setDismissable(false)
                .enableSwipeToDismiss()
                .setBackgroundColorRes(R.color.target_lineColor)
                .setIcon(R.drawable.ic_recycle_bin)
                .setIconColorFilter(0)
                .addButton("Yes", R.style.alertButtonStyle, v -> {
                    loadingDialog = FitWhizz_Dialog.fitWhizz_showDialog(this, R.layout.dialog_loding);
                    new RestCaller(this, App.getRestClient().getApiServicesforToke().deleteMeal(id, RetroClient.AddRefreshTokenHeader()), 2);
                })
                .addButton("No", R.style.alertButtonStyle, v -> {
                    Alerter.hide();
                }).show();`

**Comment by kpmmmurphy** [comment]
Hey @taimur44, 

Try removing ` .enableSwipeToDismiss()`, and adding `enableInfiniteDuration(true)` - which might help you achieve the desired effect.

**Comment by taimur44** [comment]
Hey @kpmmmurphy 
It works
thank you so much for your reply on time. 

I have a suggestion for you. 
I think you should mention all the proprieties of the library in a readme file so that everyone see What Alerter can do.

**Comment by kpmmmurphy** [comment]
@taimur44 Glad it helped! I'll look into improving the readme 😅
