### ISSUE TITLE
Alerter shows blank text in RTL languages

### ISSUE THREAD

**Issue by waseefakhtar** [Tapadoo/Alerter#190]
I use version 3.0.0 and here's how I create my alerter:

```
Alerter.create(activity)
                    .setText(activity.getString(resourceId))
                    .setBackgroundColorRes(accentBackgroundColor)
                    .setDuration(DURATION)
                    .enableIconPulse(false)
                    .enableSwipeToDismiss()
                    .show();
```

which works well for LTR languages but not RTL. Is there are workaround for this?

**Comment by kpmmmurphy** [comment]
Please update to the latest version, and try using `setContentGravity(Gravity.End)`

https://github.com/Tapadoo/Alerter/blob/01ac0d03495d3d67223db5bd4be744a0e426f958/alerter/src/main/java/com/tapadoo/alerter/Alerter.kt#L120
