### ISSUE TITLE
Alert without duration

### ISSUE THREAD

**Issue by dthib** [Tapadoo/Alerter#192]
Hi,

I would like to have an alert without any duration: the user is forced to click on it to close it. I did not find a way to do it. Is that feasible using your library?

thanks for your help and great work for this library,
Best,
Thibaut

**Comment by kpmmmurphy** [comment]
Hey @dthib!

I think this method should do the trick -

https://github.com/Tapadoo/Alerter/blob/master/alerter/src/main/java/com/tapadoo/alerter/Alerter.kt#L362

So you'd have something like -

```kotlin
Alerter.create(activity)
       .setTitle("Alert Title")
       .setText("Alert text...")
       .enableInfiniteDuration(true)
       .show()
```

**Comment by dthib** [comment]
Great, thanks a lot. I did not search enough.
Best

Le lun. 15 avr. 2019 à 17:18, Kevin Murphy <notifications@github.com> a
écrit :
