### ISSUE TITLE
Last alert come before the first alert.

### ISSUE THREAD

**Issue by samuk190** [Tapadoo/Alerter#194]
Can please someone explain why this alert doesnt work like NotificationsBanner swift?
I mean, if I use two alerts it will not wait the last one dismiss, how I can handle that

**Comment by samuk190** [comment]
How can I make it wait for next alert instead of automatically dimissing it?

**Comment by kpmmmurphy** [comment]
Hi @samuk190,

Unfortunately, this is an implementation choice to ensure only one view is added to the layout hierarchy at a time. You could add some logic to show the following Alert once the current is dismissed. 

https://github.com/Tapadoo/Alerter/blob/master/alerter/src/main/java/com/tapadoo/alerter/Alerter.kt#L386
