### ISSUE TITLE
Last version without AndroidX?

### ISSUE THREAD

**Issue by Silvia4** [Tapadoo/Alerter#200]
Can you please tell me which is the latest version without AndroidX? I can't use it in my project. Thanks

**Comment by kpmmmurphy** [comment]
Hi @Silvia4, according to the changelog, AndroidX was introduced in version 4.0.0, so the previous version to that was 3.0.2. 

https://github.com/Tapadoo/Alerter/blob/master/CHANGELOG.md#302---15112018
