### ISSUE TITLE
how to create custom layout in  java 

### ISSUE THREAD

**Issue by abhishek8506** [Tapadoo/Alerter#208]
it doest not work in koltin or java .any one help  me .

**Comment by abhishek8506** [comment]
when i download project run it it work in custom layout in koltin and java as well , but when i used it in kotlin or java in own project by add library it does not work

**Comment by kpmmmurphy** [comment]
Hi @abhishek8506, custom layouts feature is present in version 5.0.0. Which version are you currently using? Could you please add some sample code so we can debug this further. Many thanks.

**Comment by abhishek8506** [comment]
thanks for reply ,by changing version 5.0.0 it work , i have more question ,there is only one way to close alert is Aleter.hide(. fade animation occur in it) or any?.. But when we use custom layout ,we have option to  animate(own animation ) a process of closing alert by custom btn , i  think that should be add or if it is already in library then tell me what code is that. ,,overall library was great...thanks in advance..

**Comment by abhishek8506** [comment]
here i wanted click in two view in custom layout ,,but  when i want to  implement it show error
 code here.....
Alerter.create(this,R.layout.customalert).setBackgroundColorRes(android.R.color.transparent).enableVibration(true).enableSound(true).setDuration(50000).show()
                .getLayoutContainer().findViewById(R.id.constraintLayout8).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {

            }
        }).getLayoutContainer().findViewById(R.id.imageView37).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Log.d("clickdismiss", "cross btn click");
                Alerter.hide();
            }
        });


if i do any thing wrong help me...

**Comment by kpmmmurphy** [comment]
Hi @abhishek8506, I apologise but I don't understand your question.
