### ISSUE TITLE
Multiple onDraw()

### ISSUE THREAD

**Issue by luoguibin** [Tapadoo/Alerter#21]
When the Alerter is shown, the PorterDuffView will not call the method onDraw until it is hiden.
Here is my code:
```
        setContentView(new PorterDuffView(this));
        Alerter.create(this)
                .setIcon(R.mipmap.ic_launcher)
                .setText("hello world")
                .setDuration(3000)
                .setBackgroundColor(R.color.colorPrimary)
                .setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {

                    }
                })
                .show();
```

**Comment by kpmmmurphy** [comment]
Care to elaborate a little more here? I've never seen anyone do `setContentView(new PorterDuffView(this));` before.

**Comment by luoguibin** [comment]
It's a view. 
   public class PorterDuffView extends View {
   ...
    @Override
    protected void onDraw(Canvas canvas) {
        super.onDraw(canvas);
        Log.e(TAG, "drawCount " + drawCount++);
        ...
      }
   ...
   }

public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(new PorterDuffView(this));
        Alerter.create(this)
                .setIcon(R.mipmap.ic_launcher)
                .setText("hello world")
                .setDuration(3000)
                .setBackgroundColor(R.color.colorPrimary)
                .setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {

                    }
                })
                .show();
    }
}
