### ISSUE TITLE
Alerter.isShowing() is not found

### ISSUE THREAD

**Issue by pankajtalaviya97** [Tapadoo/Alerter#211]
not found and check with isshowing alert

error: cannot find symbol method isShowing()
error: cannot find symbol method hide()

help me 
thanks in advance...

**Comment by kpmmmurphy** [comment]
Hey @pankajtalaviya97, which version of the library are you using? And could you please post a code snippet below of how you're invoking these static methods, many thanks.

**Comment by pankajtalaviya97** [comment]
5.1.1 version used

**Comment by pankajtalaviya97** [comment]
implementation 'com.tapadoo.android:alerter:**1.0.6**'
this lib version are used in my project

**Comment by kpmmmurphy** [comment]
Please use the latest version of the library

```code
implementation 'com.tapadoo.android:alerter:5.1.2'
```
