### ISSUE TITLE
Delay/No animation

### ISSUE THREAD

**Issue by jaredtaskin** [Tapadoo/Alerter#223]
When I attempt to show an alert with the below code, I notice there is a long delay (4-5 seconds) after I see the log output, then the alert suddenly appears, without animation. When I swipe the alert, however, it animates off the screen like I expect. What am I doing wrong? Thanks!

```java
    @UiThread
    public void showAnnouncements(List<Announcement> announcements){

        Alerter a = Alerter.create(this.getActivity()).setTitle("Announcements").setText("App will now show announcements upon launch. Swipe up to dismiss.").enableSwipeToDismiss().setDuration(20000);

        a.setBackgroundColorInt(ContextCompat.getColor(getContext(),R.color.AMBlue));
        a.setTextAppearance(R.style.AMAnnouncementStyle);
        a.setTitleAppearance(R.style.AMAnnouncementStyle);
        a.show();
        System.out.println("Announcement: show");

    }
```

**Comment by kpmmmurphy** [comment]
Hey @jaredtaskin, sounds like you're blocking the main thread somewhere. Just from the snippet above, it looks alright - so it must be somewhere else in your app.
