### ISSUE TITLE
Set color / fontsize dynamically

### ISSUE THREAD

**Issue by dosomder** [Tapadoo/Alerter#228]
In previous version it was possible to access the text / title directly by `getTitle()` and `getText()`. You could then call for example `setTextSize()` or `setTextColor()` directly.

Now this is not possible anymore and you can only change the appearance by using a style resource with `setTextAppearance()`. However, I need to set the color dynamically. @kpmmmurphy would you accept a PR to add these getters back?

**Comment by dosomder** [comment]
@kpmmmurphy Anything against a PR?

**Comment by kpmmmurphy** [comment]
Hey @dosomder, PRs always welcome!

**Comment by bellalMohamed** [comment]
Hello, @dosomder 

I there any intention to make a PR anytime soon to add these getters back?

**Comment by dosomder** [comment]
@bellalMohamed yes I plan to do a PR in the coming week. Are you interested in this feature as well?

**Comment by bellalMohamed** [comment]
@dosomder I see you already replied to the issue on NativeScript feedback plugin which is a wrapper around this plugin 😅😅
