### ISSUE TITLE
To much buggy 

### ISSUE THREAD

**Issue by DaxeshV** [Tapadoo/Alerter#240]
to much bugs. time waster library

**Comment by dermdaly** [comment]
Hi DaxeshV, I'm not sure there's much the developers can do with your feedback.  Here's an article you may find useful.
https://medium.com/pitch-perfect/how-to-write-the-perfect-bug-report-6430f5a45cd
In addition, being open source, pull requests are accepted. I've seen many people contribute changes/fixes and enhancements to this.
Good luck!
Dermot.
