### ISSUE TITLE
Alert in BottomSheetDialogFrgament issue

### ISSUE THREAD

**Issue by shwetachauhan-simform** [Tapadoo/Alerter#247]
When we use this in **BottomSheetDialogFragment** alert hides under it. 
Any solutions for now??

**Comment by kpmmmurphy** [comment]
Hey @shwetachauhan-simform, the Alerter is technically in a different window to the Dialog, right now there is no direct solution to this. You could dismiss the bottom sheet, and then show the Alert - but this might not be the UX you're hoping for.
