### ISSUE TITLE
Migrate from JCenter

### ISSUE THREAD

**Issue by anacicconi** [Tapadoo/Alerter#255]
Hello 👋  Will this project be migrated from JCenter? Thanks!

**Comment by kpmmmurphy** [comment]
Hey @anacicconi! Yes indeed, I plan to migrate soon, to either JCenter or JitPack.io. I need to do some research on the best approach going forward!

**Comment by anacicconi** [comment]
I think you meant Maven Central, not JCenter, right?

Good to know that we will be able to keep using your library! 😉

**Comment by kpmmmurphy** [comment]
Haha, yes apologies, my mistake!! Either Maven Central or JitPack

**Comment by kpmmmurphy** [comment]
Moved to JitPack.io in PR #257. The library was already configured to be usable via JitPack, but I've refactored a few elements, and removed unneeded BinTray/JCenter code!

**Comment by anacicconi** [comment]
Thanks! 👍
