### ISSUE TITLE
Question: In-line Buttons

### ISSUE THREAD

**Issue by upseliseev** [Tapadoo/Alerter#258]
So far while using this, the buttons are always on the next line from the text. Is there a way for a single button to appear on the same line as the text, as per Android snackbar designs? 

Designs linked [here](https://material.io/components/snackbars#placement) for convenience/reference

**Comment by kpmmmurphy** [comment]
Hey @upseliseev, you could use a custom layout for this instead. 

```kotlin
 Alerter.create(this@KotlinDemoActivity, R.layout.custom_layout)
        .also { alerter ->
            val tvCustomView = alerter.getLayoutContainer()?.tvCustomLayout
            tvCustomView?.setText(R.string.with_custom_layout)
        }
        .show()

```
