### ISSUE TITLE
Possible duplication of icon names

### ISSUE THREAD

**Issue by k0shk0sh** [Tapadoo/Alerter#26]
I have an icon named __ic_notifications__ when the Alert is showing, my icon tints to white color, its due to the fact that the library has the same name as my icon. A possible solution would be to change the icons name to something that is tied to the library name.

**Comment by kpmmmurphy** [comment]
Hi @k0shk0sh - Good spot. I've updated https://github.com/Tapadoo/Alerter/pull/36
