### ISSUE TITLE
Resources$NotFoundException: Drawable com.example.myapp:drawable/button_alerter with resource ID #0x7f0800ac

### ISSUE THREAD

**Issue by parmarravi** [Tapadoo/Alerter#262]
The App is getting crashed in release apk with firebase message 

> Caused by android.content.res.Resources$NotFoundException: Drawable com.example.myapp:drawable/button_alerter with resource ID #0x7f0800ac

The Project has lib version 7.0.0

App works fine in debug version but in release apk it crashes . 
Its showing custom style for the button is not found.

Crash confirm in Android 11 and Android 10
Device OnePlus

Code

```

    public static void showTopBarAlertDialog(Activity activity, String title, String msg ,int  bckColor, TopBarAlertDialogImpl topBarAlertDialogCallback) {
        Alerter.create(activity)
                .setTitle(title)
                .setBackgroundColorRes(bckColor)
                .setIcon(R.mipmap.ic_launcher)
                .setIconColorFilter(0) // Optional - Removes white tint
                .setText(msg)
                .addButton("Go To Settings", R.style.AlertButton, new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {
                        topBarAlertDialogCallback.goToSettings();
                    }
                })
                .enableVibration(true)
                .setDismissable(true)
                .setDuration(10000)
                .enableSwipeToDismiss()
                .show();
    }

```

**Comment by kpmmmurphy** [comment]
Thanks for the details report @parmarravi. Are you using ProGuard in release?

**Comment by parmarravi** [comment]
Yes

**Comment by kpmmmurphy** [comment]
Please have a look at this article which outlines how to ensure ProGuard doesn't remove drawable resources. 

https://shrikanth.in/android/issues/2020/07/05/shrink-resources-not-found.html
