### ISSUE TITLE
Alert may has extra bottom margin when displayed with Gravity.BOTTOM

### ISSUE THREAD

**Issue by vshkl** [Tapadoo/Alerter#267]
On some devices where it is possible to switch between the system navigation bar and the physical buttons, the notification, when shown at the bottom, will have an additional margin of the height of the navigation bar, even if it is hidden.

<div style="display:flex;" >
<img src="https://user-images.githubusercontent.com/7419173/126607874-aea8d953-e16f-4f9e-a0fa-801c37b67599.jpg" width="25%" >
<img src="https://user-images.githubusercontent.com/7419173/126607887-40157b3d-aafd-45f8-b360-df88b26cf6e8.jpg" width="25%" >
</div>

1. Library version: `7.1.0`
2. Android version: `10`
3. Device: `OnePlus 5`

The issue must be [here](https://github.com/Tapadoo/Alerter/blob/d47a334e22e880643126dd3f930ca287f8559446/alerter/src/main/java/com/tapadoo/alerter/Alert.kt#L121):
```kotlin
private val navigationBarHeight by lazy {
    val dimenId = resources.getIdentifier("navigation_bar_height", "dimen", "android")
    resources.getDimensionPixelSize(dimenId)
}
```
apparently, this code will give the default value for the given device, but doesn't take into account whether it's been actually shown or not.

**Comment by kpmmmurphy** [comment]
Hey vshkl, thanks for flagging this issue, and for referencing the code which is causing it. I'd be delighted to review your pull request with a fix.

**Comment by vshkl** [comment]
Hey @kpmmmurphy, I've made a [PR](https://github.com/Tapadoo/Alerter/pull/268) that should address this issue.
Tested on several devices I have and a couple of emulators to check certain edge-cases like screens with cutouts. Will be happy to hear the feedback.
