### ISSUE TITLE
ProgressBar icon is not visible

### ISSUE THREAD

**Issue by priyanshu-lanjewar** [Tapadoo/Alerter#275]
![mobpic](https://user-images.githubusercontent.com/61533257/130728546-a9073957-2606-4262-8043-c39b7b77f6c8.png)
when Alert  of type progress is created, instead of progressbar, notification bell icon is visible.
```
Alerter.create(this@sign_in)
                .setTitle(R.string.app_name)
                .setText("Loading, Please Wait...")
                .setProgressColorInt(Color.BLUE)
                .enableProgress(true)
                .enableInfiniteDuration(true)
                .show()
```

**Comment by kpmmmurphy** [comment]
Hi @priyanshu-lanjewar, what version of the library are you using?

**Comment by priyanshu-lanjewar** [comment]
@kpmmmurphy  ohh.. Thnx i figured it out.  I changed version now so able to use it ..
