### ISSUE TITLE
alerter hide not working when called in new activity

### ISSUE THREAD

**Issue by fukemy** [Tapadoo/Alerter#276]
hi, i have alerter.show in current activity -> then i start newactivity then called hide in this activity, but it's working, did u provide way to hide all alert from one line of code? Thanks

**Comment by kpmmmurphy** [comment]
The Alert is tied to the current Activity's DecorView, so you'll have to dismiss the Alert before showing the new Activity. Perhaps using the on dismiss listener would help.

**Comment by fukemy** [comment]
@kpmmmurphy pls guide me how to use the on dismiss listener, thanks

**Comment by kpmmmurphy** [comment]
https://github.com/Tapadoo/Alerter#visibility-callbacks
