### ISSUE TITLE
Update read me for correct jitpack dependency text

### ISSUE THREAD

**Issue by hbb20** [Tapadoo/Alerter#279]
Jitpack servers `com.github.Tapadoo:Alerter:$current-version` and not `com.github.tapadoo:alerter:$current-version`.

Current readme:
![image](https://user-images.githubusercontent.com/4918760/144078846-25a71f68-f067-493b-a6d9-95424ed43662.png)

Jitpack:
![image](https://user-images.githubusercontent.com/4918760/144078913-86087f08-3638-43ca-bc71-d5e85d6664e6.png)

**Comment by roimi57** [comment]
I put the version 7.2.4 and gives me an error "Could not GET 'https://dl.bintray.com/rrsaikat/RNetwork/com/github/tapadoo/alerter/7.2.4/alerter-7.2.4.pom'. Received status code 502 from server: Bad Gateway
"

**Comment by jkeyes** [comment]
@roimi57 JFrog [shut down bintray](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/) earlier this year.

**Comment by kpmmmurphy** [comment]
Thanks for flagging this @hbb20, but the case doesn't seem to effect dependancy resolution, and the lower case formatting is more in keeping with project conventions -  so I'm gonna close this out. 

<img width="470" alt="Screenshot 2021-11-30 at 20 08 10" src="https://user-images.githubusercontent.com/6544677/144120318-1721ee58-c62d-47d5-8c7f-4cc97123d622.png">

**Comment by hbb20** [comment]
@roimi57 new versions are pushed to jitpack and not bintray. Looks like you are trying to pull a version from bintray which is not published there in the first place.

**Comment by hbb20** [comment]
@kpmmmurphy that's strange. It only worked for me when I matched jitpack casing.
