### ISSUE TITLE
Bad Gateway

### ISSUE THREAD

**Issue by roimi57** [Tapadoo/Alerter#280]
The Library gives an error "Could not GET 'https://dl.bintray.com/rrsaikat/RNetwork/com/github/tapadoo/alerter/7.1.0/alerter-7.1.0.pom'. Received status code 502 from server: Bad Gateway
"

**Comment by jkeyes** [comment]
@roimi57 JFrog [shut down bintray](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/) earlier this year.

**Comment by kpmmmurphy** [comment]
Thanks for following up @jkeyes, you're the real GOAT. 

@roimi57 BinTay (or jCenter) is now read only - so no new versions of the library can be published there. I took the design decision to move to JitPack.io for new versions. Please review the install section of our readme, and update to the latest version of the lib - https://github.com/Tapadoo/Alerter#install
