### ISSUE TITLE
Unable to implement library.

### ISSUE THREAD

**Issue by AlexandruDev** [Tapadoo/Alerter#285]
I am unable to implement this library, I'm getting this error when trying to run my project:
![image](https://user-images.githubusercontent.com/9827473/200264769-921175d1-16b7-430c-a580-cc41fe519b9b.png)

**Comment by hbb20** [comment]
It is likely that you were impacted by the gradle incident. https://status.gradle.com/incidents/9j9bx7nlwwf1 which is resolved now so you can try now.

**Comment by AlexandruDev** [comment]
Looks like that was the case, it works now.
