### ISSUE TITLE
set action?

### ISSUE THREAD

**Issue by mitchelldavis44** [Tapadoo/Alerter#31]
Would there be any way to set an action?  For example, if someone accidentally deletes something in a coordinator layout  with a snackbar I can do .setAction and set a button to undo.

**Comment by kpmmmurphy** [comment]
@mitchelldavis44 Would using the already existing on click listener functionality not suffice? Or just use a Snackbar?

**Comment by mitchelldavis44** [comment]
@kpmmmurphy that works fine, was hoping there would be some way to do it using alerter, instead of having a snackbar show also.
