### ISSUE TITLE
Expose a hide() method to hide the alert

### ISSUE THREAD

**Issue by sazid** [Tapadoo/Alerter#34]
Currently, I'm using Reflection to hide the alert, but I think it would be much better to have a public method to do it.

**Comment by EddyVerbruggen** [comment]
There already is one, but it's on `Alert` rather than on `Alerter`. Pseudo code:

```java
alert = alerter.show();
alert.hide();
```

**Comment by ulaserdegor** [comment]
Same problem.

**Comment by kpmmmurphy** [comment]
I've added this in version 2.0.0, simply call `Alerter.hide();`.
