### ISSUE TITLE
Unable to add dependency in abdroid studio

### ISSUE THREAD

**Issue by harshapulikollu** [Tapadoo/Alerter#35]
I'm unable to add this compile 'com.tapadoo.android:alerter:1.0.4' dependency in build.gradle file
I'm getting error:
 Failed to resolve: com.tapadoo.android:alerter:1.0.4 
What to do to resolve that error?

**Comment by kpmmmurphy** [comment]
Hi @harshapulikollu - could you try `com.tapadoo.android:alerter:1.0.4` instead.

**Comment by harshapulikollu** [comment]
It worked 😊 thanks for helping


On 06-Mar-2017 7:21 PM, Kevin Murphy <notifications@github.com> wrote:

Hi @harshapulikollu<https://github.com/harshapulikollu> - could you try com.tapadoo.android:alerter:1.0.4 instead.
