### ISSUE TITLE
Disable Outside Touch

### ISSUE THREAD

**Issue by dalwadi2** [Tapadoo/Alerter#37]
I want to disable the outside touch when the Alerter is showing. Can I do that with your Library?
or by Any other way?
let me know ASAP.
thanks.

**Comment by kpmmmurphy** [comment]
The library does not currently support this. You could disable touch events to views when the Alerter is show, and re-enable them when it is hidden?

**Comment by dalwadi2** [comment]
Okay, I'll do that, thanks.

**Comment by dalwadi2** [comment]
I've created that functionality and upload the pull request can you take a look @kpmmmurphy ?
thanks

**Comment by sboyokis** [comment]
I agree, we need it. Can you take a look and merge if it's ok for you ?

**Comment by Jsaiao** [comment]
+1

**Comment by limjiregister** [comment]
this function is important

**Comment by Jsaiao** [comment]
+1
