### ISSUE TITLE
Showing lots of Alerts rapidly can leave stray Alerts on screen

### ISSUE THREAD

**Issue by jonathan-caryl** [Tapadoo/Alerter#40]
In the sample app, if you press a bunch of times on DEFAULT ALERT you end up with a stack of Alerts on top of each other, it just looks like one. If you then press on e.g. COLOURED ALERT it'll call `clearCurrent` and remove the first of the existing Alerts that it finds, but when the coloured Alert goes away you can see the old Alerts still there. If you do COLOURED ALERT (slowly) enough times eventually you clear the stack of Alerts, but that doesn't seem like the right behaviour.

**Comment by mehmetsefa2644** [comment]
How can this problem be solved? I think suspending the button a few seconds after pressed might help. Any ideas?

**Comment by kpmmmurphy** [comment]
Hi @jonathan-caryl - Thanks for flagging this. I was aware of it, and it's certainly a limitation of the current design. I'll see about a fix. Have you modified the code base locally yourself to try and improve things? 

- Kevin.

**Comment by jonathan-caryl** [comment]
@kpmmmurphy I've not had time to figure out a proper fix. It seems to me you could do something like

            final ViewGroup decorView = (ViewGroup)activity.getWindow().getDecorView();
            for (int i = 0; i < decorView.getChildCount(); i++) {
                View childView = decorView.getChildAt(i);
                if (childView instanceof Alert) {
                    Alert alert = (Alert)childView;
                    Log.d(LOG_TAG, ""+alert);
                }
            }

in `clearCurrent` to find all the children that needed to be cleared, perhaps you should just be calling `hide()` on the `Alert` to make it go away. I guess you'd need to add some flag inside `Alert` so that if you end up calling `hide()` on one that's already executing the hide animation, than it'd no try to restart it.

**Comment by Jsaiao** [comment]
+1

**Comment by kpmmmurphy** [comment]
Thanks for all the comment. I've updated this in version 1.0.8. Now, when we ensure all alerts are removed, by first fading them, then removing them from the DecorView.
