### ISSUE TITLE
Button options

### ISSUE THREAD

**Issue by Jsaiao** [Tapadoo/Alerter#41]
Hello friend, incredible LIB that you have created, I've been using it in a project and would like to know if it's possible to include buttons inside the notification. Example: When a notification appears, there is also option A and option B each with a different activity.

Thanks for help. ;)

**Comment by MartinNemec** [comment]
+1

**Comment by kpmmmurphy** [comment]
Hi @Jsaiao, thanks for you comment. No functionality for this at the moment. It would likely require the Alerter to take a custom XML layout, so it's more configurable.
