### ISSUE TITLE
No icon option

### ISSUE THREAD

**Issue by zalito12** [Tapadoo/Alerter#42]
Hi! Is there a way to don't show any icon? I tried "null" and color trasparent but it has to be a Drawable so it doesn't work. I could make a trasparent drawable but it would be very easy to check if drawable exists or is null and set icon to null if that.
If there is a way I couldn't find it and if there is not we could add that option.

**Comment by kpmmmurphy** [comment]
Good idea - I've included this in version 1.0.8, see method below. 

https://github.com/Tapadoo/Alerter/blob/master/alerter/src/main/java/com/tapadoo/alerter/Alerter.java#L326
