### ISSUE TITLE
add RTL support

### ISSUE THREAD

**Issue by iceberg1369** [Tapadoo/Alerter#59]
add setLayoutDirection so that we could change layout direction for RTL texts in non RTL phones as well

**Comment by MoustaphaHadeed** [comment]
It's already supporting RTL, just make sure to set your activity layout direction to RTL:

```
public static void forceLayoutDirectionToRtl(Activity activity) {
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR1) {
        getWindow().getDecorView().setLayoutDirection(View.LAYOUT_DIRECTION_RTL);
    }
}
```

![screenshot_2017-06-04-23-24-02](https://cloud.githubusercontent.com/assets/11995027/26765125/ee3b28b2-497d-11e7-8ef9-a3d1f29d8f10.png)

**Comment by MoustaphaHadeed** [comment]
It's already supporting RTL, just make sure to set your activity layout direction to RTL:

```
public static void forceLayoutDirectionToRtl(Activity activity) {
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR1) {
        activity.getWindow().getDecorView().setLayoutDirection(View.LAYOUT_DIRECTION_RTL);
    }
}
```

![screenshot_2017-06-04-23-24-02](https://cloud.githubusercontent.com/assets/11995027/26765125/ee3b28b2-497d-11e7-8ef9-a3d1f29d8f10.png)

**Comment by AlaaZarifa** [comment]
@MustaphaHadid hey man, your method didn't work because I'm already forcing rtl layout in the splash activity with this code..
```
Resources res = getResources();
    Configuration newConfig = new Configuration( res.getConfiguration() );
    Locale locale = new Locale("ar");
    newConfig.locale = locale;
    newConfig.setLayoutDirection( locale );
    res.updateConfiguration( newConfig, null );
```

 it basically forces rtl layout for every activity ! 
Can you help me finding a work around !?

**Comment by MustaphaHadid** [comment]
Try this,

`Resources appResources = app.getResources();
    DisplayMetrics displayMetrics = appResources.getDisplayMetrics();
    Configuration resConfiguration = appResources.getConfiguration();
    resConfiguration.setLayoutDirection(new Locale(lang)); `
