### ISSUE TITLE
Dectect Running Alerter

### ISSUE THREAD

**Issue by dhamdani666** [Tapadoo/Alerter#61]
How to know alerter is running  ? 
isShowing() ?

**Comment by kpmmmurphy** [comment]
There's not proper functionality for this right now - I'll add it as an enhancement.

**Comment by kpmmmurphy** [comment]
This has been added in version 2.0.0. Simply call `Alerter.isShowing();` 😬

**Comment by nithinkolekar** [comment]
is that mean we can show Alerter one after another?
