### ISSUE TITLE
Custom font size

### ISSUE THREAD

**Issue by nick-iCars** [Tapadoo/Alerter#65]
Our app is viewed by drivers and the default text is a bit  too small. Any chance of getting a jumbo text mode?

Thank you

BTW this is a very nicely designed component and api. Thanks for creating it.

**Comment by kpmmmurphy** [comment]
Hi Nick,

Not at the moment, but I'll add it as an enhancement in version 2. You could always fork the repo and modify the text size to suit your needs for now.

**Comment by nick-iCars** [comment]
Kevin,
Thanks for the response. If I end up implementing it ill submit a pull req.

**Comment by kpmmmurphy** [comment]
Present in version 2.0.0.

**Comment by nick-iCars** [comment]
You rock!
