### ISSUE TITLE
Swipe to dismiss or another button to close?

### ISSUE THREAD

**Issue by dskwon19** [Tapadoo/Alerter#66]
I think it would be a great feature to be able to swipe and dismiss the alert, in case onClick is used for something else. 

Or another close button at the top right if that's easier.

**Comment by kpmmmurphy** [comment]
Hi David, Swipe to dismiss would be a great addition. Have you written any code for this?

**Comment by dskwon19** [comment]
No I have not. I would if I could find some spare time!

**Comment by dskwon19** [comment]
I actually have some code if you'd like to take a look

**Comment by kpmmmurphy** [comment]
Absolutely, put in a pull request and we can take it from there!

**Comment by dskwon19** [comment]
I've posted the PR

**Comment by kpmmmurphy** [comment]
Updated in https://github.com/Tapadoo/Alerter/pull/69, and available version 1.0.9 and above.
