### ISSUE TITLE
Failed to resolve: com.tapadoo.android:alerter:1.0.9

### ISSUE THREAD

**Issue by anujdeo** [Tapadoo/Alerter#67]
Hello,

I am not able to load this library in my code.
I get this error when I include it in gradle: **Failed to resolve: com.tapadoo.android:alerter:1.0.9**

My Gradle version : 2.2.0
My Android Studio version : 2.3.1

**com.tapadoo.android:alerter:1.0.8 works**

**Comment by kpmmmurphy** [comment]
Hi @anujdeo - The last version didn't upload to BinTray so you'll have to rely on 1.0.8 for now I'm afraid. I'll update as soon as I can.

**Comment by anujdeo** [comment]
Thanks for prompt reply. Yes I am using 1.0.8

**Comment by kpmmmurphy** [comment]
@anujdeo This has been fixed in https://github.com/Tapadoo/Alerter/pull/69, so I'm going to close out this issue. Thanks again for flagging.
