### ISSUE TITLE
Request to add OK-Cancel Buttons at bottom

### ISSUE THREAD

**Issue by anujdeo** [Tapadoo/Alerter#68]
Hello,
This is an amazing library I just loved it. 
It has a potential to replace boring Alert/Popups. 

I request you to Add Buttons on it.

**Comment by kpmmmurphy** [comment]
Hi @anujdeo - You can add an OnClickListener to it, which acts in the same way. What did you have in mind?

**Comment by anujdeo** [comment]
@kpmmmurphy Yes I used onClickListener. But suppose you have 2 different operations to be perform after click then it would be great if we have buttons on it.
E.g. Suppose I want to use Alerter as "Delete Confirmation" - Then I should have "Delete" and "Cancel" buttons on it. 

Basically what I think is your library is a Beautiful replacement for Alertbox.

**Comment by rojalearner** [comment]
hai,
If i use your library in @Fullscreen activity then alert have too empty space at top of alert

**Comment by waseefakhtar** [comment]
I agree with the choice of adding buttons on it. Though I'm aware of adding OnClickListener to make it perform actions, but an addition of the button might make more sense to users. Do you plan on implementing it?

**Comment by kpmmmurphy** [comment]
I definitely agree it would be an handy feature! I'll prioritize this in the next release. :rocket:

**Comment by waseefakhtar** [comment]
I was wondering if this has been worked on in the new release.

**Comment by kpmmmurphy** [comment]
Hi @waseefakhtar, this feature is available in versionj 3.0.0, but currently requires Kotlin, and Constraint Layout as a dependency.
