### ISSUE TITLE
Can update text or icon after showing?

### ISSUE THREAD

**Issue by williambao** [Tapadoo/Alerter#76]
Hi,
It's can update title/text/icon after the `Alerter` showing?
In my app, use `Alerter` to notify user when receive new audio message. 
And I want to show audio playing duration in `text`. 

Thanks,

**Comment by kpmmmurphy** [comment]
Hi William, 

This isn't support, however you could try finding the Alert's TextView, by calling findViewById(R.id.tvText) when it's showing, and update it as you would any other text view. Just make sure to null check it. 

See here - 

https://github.com/Tapadoo/Alerter/blob/master/alerter/src/main/res/layout/alerter_alert_view.xml#L68

**Comment by ihewro** [comment]
I think altering text while it showing is a necessary inteface especially when using `progress type Alerter `
