### ISSUE TITLE
setIcon crash

### ISSUE THREAD

**Issue by liangweihao** [Tapadoo/Alerter#78]
ndroid.content.res.Resources$NotFoundException: File res/drawable-xxhdpi-v4/   4.4.2 huawei crash

**Comment by kpmmmurphy** [comment]
I'll need some more detail on this. Can you post the code where you're invoking the Alerter please.

**Comment by sergii-frost** [comment]
I had the same issue, it is happening on Android 4.x - 5.x

That is happening in case if you try to use .png as a drawable.

@liangweihao if you switch to .svg instead (Android Studio supports .svg for import as Vector Assets), and do a bit of additional setup in the project to be backwards compatible with Vector drawables, you will get it working. 

Changes needed in project to work on older Android versions:

1. build.gradle

```
defaultConfig {
    vectorDrawables.useSupportLibrary = true
}
```

2. YourApp class (which extends Application)

```
//in onCreate() method
AppCompatDelegate.setCompatVectorFromResourcesEnabled(true);
```

**Comment by sergii-frost** [comment]
@kpmmmurphy I have a question to you as well, please let me know if I should have a separate issue for it, but is it possible to change colour for the icon itself? 

I have a need to have light background for the Alerter message, but icon is always white, even if I explicitly use coloured drawable resource.

**Comment by sijojosep** [comment]
I had the same issue .

NotFoundException for com.aitrich.android.orderpro
                                                                    android.content.res.Resources$NotFoundException: File res/drawable-xxhdpi-v4/ic_map_marker_white_48dp.png from xml type xml resource ID #0x7f020102

**Comment by kpmmmurphy** [comment]
I've updated this in version 2.0.1. @sergii-frost no support for this, but feel free to prepare a PR and I'll review it.
