### ISSUE TITLE
There is an extra bottom shadow

### ISSUE THREAD

**Issue by jaychang0917** [Tapadoo/Alerter#79]
Hi, I run the demo project and found the view has an extra bottom shadow. How to remove it? 

My device: Samsung note4, Android 6.0.1

The screenshot :
http://imgur.com/vMk5LVK

**Comment by patrickpissurno** [comment]
Same problem here. Any updates?

**Comment by kpmmmurphy** [comment]
Thanks for flagging this @jaychang0917  & @patrickpissurno, I've updated this in version 2.0.1 so it should no longer occur.
