### ISSUE TITLE
Global alerter

### ISSUE THREAD

**Issue by anderscheow** [Tapadoo/Alerter#82]
Is it possible to create an global alerter regardless on which activity?

**Comment by kpmmmurphy** [comment]
Unfortunately no, it's not possible as each Activity has its own Window/DecorView which the Alerter gets attached to.

**Comment by bartarapp** [comment]
Unfortunately no, But I've summarized the code more and I've defined it in the Global class and I'm just sending activity and text.


public void myTaost(Activity activity, String desc) {
        Typeface mTypeface = Typeface.createFromAsset(activity.getAssets(), "fonts/yourFont.ttf");

        Alerter.create(activity)
                .setTitle("Alert")
                .setTextTypeface(mTypeface)
                .setTitleTypeface(mTypeface)
                .setContentGravity(Gravity.RIGHT)
                .setBackgroundColorInt(Color.parseColor("#A1374C"))
                .enableSwipeToDismiss()
                .setText(desc)
                .show();
    }
