### ISSUE TITLE
Progress bar is not shown

### ISSUE THREAD

**Issue by JonathanSilvaTI** [Tapadoo/Alerter#85]
I used:
.setDuration(2000)
.enableProgress(true)
.show()
but the bar is not displayed
(Android 5.0.0 API 21)

**Comment by kpmmmurphy** [comment]
I've updated this in version 2.0.1. Try changing the colour to something more contrasting.

**Comment by JonathanSilvaTI** [comment]
I updated the lib and changed the color but nothing to show the progress bar

**Comment by jonathansilva** [comment]
I have the same problem
the version is 2.0.2

`public static void alerter(Integer title, Activity activity) {
        Alerter.create(activity)
                .setTitle(title)
                .setBackgroundColorRes(R.color.colorPrimary)
                .setDuration(2000)
                .enableProgress(true)
                .setProgressColorRes(R.color.colorGreenDark)
                .show();
    }`
