### ISSUE TITLE
Alerter show fail

### ISSUE THREAD

**Issue by Bobyang912** [Tapadoo/Alerter#86]
Alerter mlerter;
in onCreate()：
mlerter = Alerter.create(this)
                .setText("text")
                .setIcon(R.drawable.alerter_ic_notifications)
                .setBackgroundColor(R.color.success);

when button click,i call
mlerter.show() to show the Alerter,It was successful for the first time, but then it failed

**Comment by kpmmmurphy** [comment]
Hi Bob, the current implementation does not cater for this. I'd recommend adding a method for creating the Alerter, and pass in a String which you'd like to display, such as - 

```java
private void showSuccess(final String text) {
  Alerter.create(this)
  .setText(text)
  .setIcon(R.drawable.alerter_ic_notifications)
  .setBackgroundColor(R.color.success)
  .show();
}
```

This way, there is no need for holding a reference to an Alerter instance, and the Alert will show each time.

**Comment by Bobyang912** [comment]
This raises a problem. If I call this method（showSuccess(final String text)） multiple times in my application, it will generate multiple instances of Alerter without getting the release. Is that a problem?

**Comment by kpmmmurphy** [comment]
The library handles this, so it's not a problem.
