### ISSUE TITLE
Statusbar remains visible for AppCompatActivity

### ISSUE THREAD

**Issue by anujdeo** [Tapadoo/Alerter#89]
If I use Alerter in AppCompatActivity it is created from below of the System Statusbar. Is there any setting to fix this?
Check this screenshot for details:
https://drive.google.com/file/d/0B22kbTLSeBysdUhmZlhzVEJDWEdCOF9PV2Nsbk5jLWFzUVo4/view?usp=sharing

**Comment by kpmmmurphy** [comment]
Hi @anujdeo - Are you setting any styles to that activity? Or configuring your window in any way? Feel free to post some code here so I can take a look.

**Comment by TCQQ** [comment]
I also have same problem, this is my activity theme
![qq 20171028135038](https://user-images.githubusercontent.com/10644057/32131679-fec79c20-bbe6-11e7-9ab6-0d6aa30f8800.png)


    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">

        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>

    </style>

**Comment by TCQQ** [comment]
<?xml version="1.0" encoding="utf-8"?>
<android.support.design.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/cl_root_layout"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <android.support.design.widget.AppBarLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content">

        <include layout="@layout/content_toolbar" />

    </android.support.design.widget.AppBarLayout>

</android.support.design.widget.CoordinatorLayout>

**Comment by kpmmmurphy** [comment]
Hi @TCQQ - Where are you calling the Alerter from?

**Comment by TCQQ** [comment]
In AppCompatActivity

    public void showAlert(String title, String text, int backgroundColor) {
        if (!Alerter.isShowing()) {
            Alerter.create(this)
                    .setTitle(title)
                    .setText(text)
                    .setBackgroundColorRes(backgroundColor)
                    .setIcon(R.drawable.alerter_ic_face)
                    .show();
        }
    }

**Comment by kpmmmurphy** [comment]
I've added a fix for this into version 2.0.2, https://github.com/Tapadoo/Alerter/blob/master/CHANGELOG.md
