### ISSUE TITLE
Publish to bintray/jitpack

### ISSUE THREAD

**Issue by nisrulz** [Tapadoo/Alerter#9]
As of now the integration of the lib requires that one has to checkout the code and include the module. 
 If published to jitpack/bintray other devs need only include a single line for the  dependency and gradle would pull the dependency.

**Comment by roughike** [comment]
> As of now the integration of the lib requires that one has to checkout the code and include the module.

That's not true: see the end of the README:

```groovy
compile 'com.tapadoo.android:alerter:1.0.1'
```

That line could be at the top though.
