### ISSUE TITLE
How to use into Adapter

### ISSUE THREAD

**Issue by tellfa** [Tapadoo/Alerter#90]
Hi, thanks for this great library.
but how can i use this library into Adapter. 
i use this code : `Alerter.create(context)` but does not accept context.

**Comment by kpmmmurphy** [comment]
Hi @tellfa - You could pass the Activity into the Adapter via it's constructor, and that way you be able to call it.

**Comment by tellfa** [comment]
are this true way?!

**Comment by anujdeo** [comment]
I think yes. Send Activity context through your Adapter's Constructor.
